server:
  port: ${PORT:10000}

spring:
  datasource:
    url: jdbc:${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jira:
  base-url: ${JIRA_BASE_URL}
  email: ${JIRA_EMAIL}
  api-token: ${JIRA_API_TOKEN}
  comment-enabled: ${JIRA_COMMENT_ENABLED:false}

groq:
  api-key: ${GROQ_API_KEY}

logging:
  level:
    com.qa.qa_orchestrator_service: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"