server:
  port: ${PORT:10000}

jira:
  base-url: ${JIRA_BASE_URL}
  email: ${JIRA_EMAIL}
  api-token: ${JIRA_API_TOKEN}

groq:
  api-key: ${GROQ_API_KEY}

logging:
  level:
    com.qa.qa_orchestrator_service: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"